name: phone_number_text_field
description: Simple and customizable flutter package to enter phone number in international format using Google's lib phone number.
version: 0.1.0
homepage: https://github.com/Soufiene-Hmila/phone_number_text_field.git

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  collection: ^1.18.0

  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

# The following section is specific to Flutter packages.
flutter:

  plugin:
    platforms:
      android:
        package: com.dmsh.phone_number_text_field
        pluginClass: PhoneNumberTextFieldPlugin
      ios:
        pluginClass: PhoneNumberTextFieldPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/flags/


