name: phone_number_text_field
description: Simple and customizable flutter package to enter phone number in international format using Google's lib phone number.
version: 0.0.5
homepage: https://github.com/Soufiene-Hmila/phone_number_text_field.git

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter packages.
flutter:

  plugin:
    platforms:
      android:
        package: com.dmsh.phone_number_text_field
        pluginClass: PhoneNumberTextFieldPlugin
      ios:
        pluginClass: PhoneNumberTextFieldPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/flags/


